;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; WORKSPACES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true

label-active = %index%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-padding = 2

label-occupied = %index%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.white}
label-urgent-padding = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ACTIVE WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/xwindow]
type = internal/xwindow

label = %title:0:65:...%
label-foreground = ${colors.otherBlue}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; WIFI
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/wlan]
type = internal/network

interface-type = wireless
interval = 2

format-connected = %{A1:bash ~/dotfiles/scripts/rofi-wifi-menu.sh:}<ramp-signal> <label-connected>%{A}
format-disconnected = %{A1:bash ~/dotfiles/scripts/rofi-wifi-menu.sh:}󰤭 Offline%{A}

label-connected = %essid%
label-connected-foreground = ${colors.foreground}

format-disconnected-foreground = ${colors.disabled}

ramp-signal-foreground = ${colors.foreground}
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; AUDIO
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/pulseaudio]
type = internal/pulseaudio

format-volume = 󰕾 <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.white}

label-muted = 󰖁 Muted
label-muted-foreground = ${colors.disabled}

click-right = pavucontrol

scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%
click-middle = pactl set-sink-mute @DEFAULT_SINK@ toggle

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; BRIGHTNESS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/brightness]
type = internal/backlight

card = intel_backlight

enable-scroll = true

format = 󰍹 <label>

label = %percentage%%
label-foreground = ${colors.yellow}

scroll-up = brightnessctl set +2%
scroll-down = brightnessctl set 2%-

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MEMORY
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/memory]
type = internal/memory

interval = 2

format = 󰍛 <label>

label = %gb_used:1:4%G/%gb_total:1:4%G
label-foreground = ${colors.aqua}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; CPU
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/cpu]
type = internal/cpu

interval = 2

format =  <label>

label = %percentage%%
label-foreground = ${colors.orange}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; BATTERY
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/battery]
type = internal/battery

battery = BAT1
adapter = ACAD

full-at = 98

format-charging = ⚡ <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = 󰁹 100%

label-charging = %percentage%%
label-discharging = %percentage%%

label-charging-foreground = ${colors.green}
label-discharging-foreground = ${colors.green}

ramp-capacity-foreground = ${colors.green}

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁻
ramp-capacity-2 = 󰁼
ramp-capacity-3 = 󰁽
ramp-capacity-4 = 󰁾
ramp-capacity-5 = 󰁿
ramp-capacity-6 = 󰂀
ramp-capacity-7 = 󰂁
ramp-capacity-8 = 󰁹

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; TEMPERATURE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/temperature]
type = internal/temperature

thermal-zone = 3
interval = 2

base-temperature = 30
warn-temperature = 80

format = <ramp> <label>

label = %temperature-c%
label-foreground = ${colors.lighter}

label-warn = %temperature-c%
label-warn-foreground = ${colors.alert}

ramp-foreground = ${colors.lighter}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DATE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date]
type = internal/date

interval = 1

time = %a %d %b  %H:%M

format = 󰥔 <label>

label = %time%
label-foreground = ${colors.foreground}
