[colors]
background = #141415
background-alt = #252530
foreground = #cdcdcd
primary = #6e94b2
secondary = #bb9dbd
pink = #fcb0b3
alert = #d8647e
disabled = #606079
lightBlue=#90DDF0
otherBlue = #ADB6C4
green = #7fa563
blue = #6e94b2
aqua = #aeaed1
orange = #f3be7c
purple = #bb9dbd
red = #d8647e
yellow = #f3be7c
white = #d7d7d7
brown = #402E2A
slateBlue= #4F5D75
lighter = #59BA81


[bar/bar]
monitor=eDP-1
height = 25
radius = 8
offset-x=2%
offset-y=2
width = 96%
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
line-size = 2
; border-size = 0
; border-color = ${colors.primary}
padding-left = 2
padding-right = 2
fixed-center = true
module-margin = 1
font-0 = JetBrainsMono Nerd Font:size=9:style=bold;2
font-1 = JetBrainsMono Nerd Font:size=10;2
font-2 = JetBrainsMono Nerd Font:size=11;2
modules-left = xworkspaces
modules-center = date
modules-right = memory brightness battery pulseaudio wlan
cursor-click = pointer
cursor-scroll = default
enable-ipc = true
wm-restack = i3
override-redirect = true

[module/music]
type = custom/script

exec = ~/dotfiles/scripts/player.sh
interval = 1

format = <label>
format-background = ${colors.background-alt}
format-foreground = ${colors.pink}
format-padding = 2

label = %output%

click-left = playerctl play-pause
click-right = playerctl next

scroll-up = playerctl next
scroll-down = playerctl previous

[module/temperature]
type = internal/temperature
interval = 2
thermal-zone=3
base-temperature = 30
warn-temperature = 80
label-foreground = ${colors.lighter}
label-warn-foreground = ${colors.lighter}
format = <ramp> <label>
label = %temperature-c%
format-warn = <ramp> <label-warn>
label-warn = %temperature-c%
ramp-foreground=${colors.lighter}
ramp-0 = %{T3}%{T-}
ramp-1 = %{T3}%{T-}
ramp-2 = %{T3}%{T-}
ramp-3 = %{T3}%{T-}
ramp-4 = %{T3}%{T-}


[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98
format-charging = <animation-charging> 
format-discharging = <ramp-capacity> 
format-full = <ramp-capacity> 
label-charging-foreground=${colors.white}
label-discharging-foreground = ${colors.white}
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
ramp-capacity-foreground = ${colors.white}

ramp-capacity-0 = %{T3}󰁻%{T-}
ramp-capacity-1 = %{T3}󰁼%{T-}
ramp-capacity-2 = %{T3}󰁽%{T-}
ramp-capacity-3 = %{T3}󰁾%{T-}
ramp-capacity-4 = %{T3}󰁿%{T-}
ramp-capacity-5 = %{T3}󰂀%{T-}
ramp-capacity-6 = %{T3}󰂁%{T-}
ramp-capacity-7 = %{T3}󰂂%{T-}
ramp-capacity-8 = %{T3}󰁹%{T-}
animation-charging-foreground = ${colors.white}
animation-charging-0 = %{T3}󰂆%{T-}
animation-charging-1 = %{T3}󰂇%{T-}
animation-charging-2 = %{T3}󰂈%{T-}
animation-charging-3 = %{T3}󰢝%{T-}
animation-charging-4 = %{T3}󰂉%{T-}
animation-charging-5 = %{T3}󰢞%{T-}
animation-charging-6 = %{T3}󰂋%{T-}
animation-charging-7 = %{T3}󰂋%{T-}
animation-charging-framerate = 750

[module/xworkspaces]
type = internal/xworkspaces
label-active = 
# label-active-underline = ${colors.primary}
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = %index%
label-occupied-padding = 1
label-occupied-foreground = ${colors.disabled}

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %index%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

; [module/pulseaudio]
; type = internal/pulseaudio
; format-volume-prefix = %{T2}󰕾 %{T-}
; format-volume-prefix-foreground = ${colors.white}
; format-volume = <label-volume>
; label-volume = %percentage:2%%
; label-muted = %{T2}󰖁 %{T-}
; label-muted-foreground = ${colors.disabled}
; click-right = pavucontrol
; label-volume-foreground = ${colors.white}
;
[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume>
ramp-volume-0 = %{T3}󰕿%{T-}
ramp-volume-1 = %{T3}󰖀%{T-}
ramp-volume-2 = %{T3}󰕾%{T-}
ramp-volume-foreground = ${colors.white}
label-muted = %{T3}󰖁%{T-}
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol
scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%
click-middle = pactl set-sink-mute @DEFAULT_SINK@ toggle

[module/memory]
type = internal/memory
interval = 0.5
format-prefix = %{T2}󰾆 %{T-}
format-prefix-foreground = ${colors.aqua}
label = %gb_used:1:4%G/%gb_total:1:4%G
label-foreground = ${colors.aqua}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = %{T2} %{T-}
format-prefix-foreground = ${colors.orange}
label = %percentage:1%%

[module/wlan]
type = internal/network
interface-type = wireless
interval = 0.5
format-connected = %{A1:bash ~/dotfiles/scripts/rofi-wifi-menu.sh:}<ramp-signal>%{A}
format-disconnected = %{A1:bash ~/dotfiles/scripts/rofi-wifi-menu.sh:}%{T3}󰤭 %{T-}%{A}
format-disconnected-foreground = ${colors.disabled}
ramp-signal-foreground = ${colors.white}
label-connected=%essid%
ramp-signal-0 = %{T3}󰤯 %{T-}
ramp-signal-1 = %{T3}󰤟 %{T-}
ramp-signal-2 = %{T3}󰤢 %{T-}
ramp-signal-3 = %{T3}󰤥 %{T-}
ramp-signal-4 = %{T3}󰤨 %{T-}
ramp-signal-5 = %{T3}󰤨 %{T-}

[module/brightness]
type = internal/backlight
card = intel_backlight
enable-scroll = true
format-prefix = %{T2}󰍹 %{T-}
format-prefix-foreground = ${colors.yellow}
label = %percentage%%
label-foreground = ${colors.yellow}
scroll-up = brightnessctl set +2%
scroll-down = brightnessctl set 2%-

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.foreground}

[module/logout]
type = custom/text
content = %{T2}%{T-}
content-foreground = ${colors.red}
click-left = ~/.config/i3/power.sh logout

[settings]
screenchange-reload = true
