
[colors]
background = #141415
background-alt = #252530
foreground = #cdcdcd

primary = #6e94b2
secondary = #bb9dbd

alert = #d8647e
disabled = #606079

green = #7fa563
blue = #6e94b2
aqua = #aeaed1
orange = #f3be7c
purple = #bb9dbd
red = #d8647e
yellow = #f3be7c
white = #d7d7d7

[bar/bar]
monitor=eDP-1
height = 26
radius = 0px
width = 100%
center = true
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
line-size = 2
border-size = 0
border-color = ${colors.white}
padding-left = 5
padding-right = 5
fixed-center = true
module-margin = 1
font-0 = JetBrainsMono Nerd Font:size=10;2
font-1 = JetBrainsMono Nerd Font:size=11;2
modules-left = xworkspaces
modules-center = date
modules-right = pulseaudio memory cpu brightness battery wlan logout
cursor-click = pointer
cursor-scroll = default
enable-ipc = true
wm-restack = i3
; override-redirect = true

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
full-at = 98
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 100%

ramp-capacity-foreground = ${colors.green}

ramp-capacity-0 = %{T2}󰁻%{T-}
ramp-capacity-1 = %{T2}󰁼%{T-}
ramp-capacity-2 = %{T2}󰁽%{T-}
ramp-capacity-3 = %{T2}󰁾%{T-}
ramp-capacity-4 = %{T2}󰁿%{T-}
ramp-capacity-5 = %{T2}󰂀%{T-}
ramp-capacity-6 = %{T2}󰂁%{T-}
ramp-capacity-7 = %{T2}󰂂%{T-}
ramp-capacity-8 = %{T2}󰁹%{T-}
animation-charging-foreground = ${colors.green}
animation-charging-0 = %{T2}󰂆%{T-}
animation-charging-1 = %{T2}󰂇%{T-}
animation-charging-2 = %{T2}󰂈%{T-}
animation-charging-3 = %{T2}󰢝%{T-}
animation-charging-4 = %{T2}󰂉%{T-}
animation-charging-5 = %{T2}󰢞%{T-}
animation-charging-6 = %{T2}󰂋%{T-}
animation-charging-7 = %{T2}󰂋%{T-}
animation-charging-framerate = 750

[module/xworkspaces]
type = internal/xworkspaces

label-active = %index%
label-active-underline = ${colors.primary}
label-active-foreground = ${colors.white}
label-active-padding = 1

label-occupied = %index%
label-occupied-padding = 1
label-occupied-foreground = ${colors.foreground}

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %index%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = %{T2}󰕾 %{T-}
format-volume-prefix-foreground = ${colors.blue}

format-volume = <label-volume>
label-volume = %percentage:2%%

label-muted = %{T2}󰖁 %{T-}
label-muted-foreground = ${colors.disabled}

click-right = pavucontrol

[module/memory]
type = internal/memory
interval = 0.5

format-prefix = %{T2} %{T-}
format-prefix-foreground = ${colors.aqua}

label = %percentage_used:3%%

[module/cpu]
type = internal/cpu
interval = 2

format-prefix = %{T2} %{T-}
format-prefix-foreground = ${colors.orange}

label = %percentage:1%%

[module/wlan]
type = internal/network
interface-type = wireless
interval = 2.0

format-connected = <ramp-signal>

format-disconnected = %{T2}󰤭 %{T-}
format-disconnected-foreground = ${colors.disabled}

ramp-signal-foreground = ${colors.blue}

ramp-signal-0 = %{T2}󰤯 %{T-}
ramp-signal-1 = %{T2}󰤟 %{T-}
ramp-signal-2 = %{T2}󰤢 %{T-}
ramp-signal-3 = %{T2}󰤥 %{T-}
ramp-signal-4 = %{T2}󰤨 %{T-}
ramp-signal-5 = %{T2}󰤨 %{T-}

[module/brightness]
type = internal/backlight
card = intel_backlight

enable-scroll = true

format-prefix = %{T2}󰍹 %{T-}
format-prefix-foreground = ${colors.yellow}

label = %percentage:2%%

scroll-up = brightnessctl set +2%
scroll-down = brightnessctl set 2%-

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.foreground}

[module/logout]
type = custom/text

content = %{T2}%{T-}
content-foreground = ${colors.red}

click-left = ~/.config/i3/power.sh logout

[settings]
screenchange-reload = true
pseudo-transparency = true
