include-file = ~/dotfiles/polybar/topbarModule.ini

[bar/bar]
monitor=eDP-1
height = 25
radius = 8
offset-x=2%
offset-y=2
width = 96%
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
line-size = 2
; border-size = 0
; border-color = ${colors.primary}
padding-left = 2
padding-right = 2
fixed-center = true
module-margin = 1
font-0 = JetBrainsMono Nerd Font:size=9:style=bold;2
font-1 = JetBrainsMono Nerd Font:size=10;2
font-2 = JetBrainsMono Nerd Font:size=11;2
modules-left = xworkspaces
modules-center = date
modules-right = memory brightness battery pulseaudio wlan 
cursor-click = pointer
cursor-scroll = default
enable-ipc = true
wm-restack = i3
override-redirect = true

